### ISSUE TITLE
How to pass data to a coordinator?

### ISSUE THREAD

**Issue by Gargo** [felilo/ALCoordinator#46]
There is no info about how to pass data between coordinators.

And in the same time:
```
open func start(animated: Bool = true ) {
    fatalError("start(animated:) has not been implemented")
  }
```

method seems to be optional but you declared it like a required one.

**Comment by felilo** [comment]
If you need to pass data, you can use dependency injection among them. 
For example:

`
func showCoordinatorB(user: User) {
  let coordinator = CoordinatorB(user: user)
  coordinator.start()
}
`
Here you have an implementation example of ALCoordinator
https://github.com/felilo/TestCoordinatorLibrary
