### ISSUE TITLE
Feature request - push coordinator

### ISSUE THREAD

**Issue by Gargo** [felilo/ALCoordinator#47]
For example I need to push authorisation flow. I could place it into a separate "authorisation coordinator" but it seems to be not implemented

**Comment by felilo** [comment]
Here you have an implementation example of ALCoordinator
https://github.com/felilo/TestCoordinatorLibrary

**Comment by Gargo** [comment]
@felilo I see `presentCoordinator` in it only. But I don't need to `present` I need to `push` into the same `navigation controller`

**Comment by felilo** [comment]
If you need to push a view into a navigation stack, you can play with the **var transition: NavigationTransitionStyle** use something like this:

´´´
enum OnboardingRouter: NavigationRouter {
    
    case firstStep(viewModel: FirstViewModel)
    case promoAd
    case secondStep(viewModel: SecondViewModel)
    
    // MARK: NavigationRouter
    var transition: NavigationTransitionStyle {
        switch self {
            case .firstStep, .secondStep:
                return .push
            case . promoAd: return .present
        }
    }
    
    func view() -> any View {
        switch self {
            case .firstStep(let vm):
                return FirstView(viewModel: vm)
            case .secondStep(let vm):
                return SecondView(viewModel: vm)
            case .promoAd:
                return PromoAdView()
        }
    }
}
´´´

**Comment by felilo** [comment]
If you need a new Coordinator to have a behavior like push instead of present you can make a custom animation. Please check UIViewControllerAnimatedTransitioning documentation

https://developer.apple.com/documentation/uikit/uiviewcontrolleranimatedtransitioning
