### ISSUE TITLE
Switch between tabs programmatically?

### ISSUE THREAD

**Issue by Gargo** [felilo/ALCoordinator#54]
For example from your readme:
```
enum HomeRouter: CaseIterable, TabbarPage {
case marketplace
  case settings

  // MARK: NavigationRouter

  func coordinator(parent: Coordinator) -> Coordinator {
    switch self {
      case .settings:
        return SettingCoordinator(parent: parent)
      case .marketplace:
        return MarketplaceCoordinator(parent: parent)
    }
  }
...
}
```

```
class HomeCoordinator: TabbarCoordinator<HomeRouter> {

  public init(parent: Coordinator) {
    let pages: [Router] = [.marketplace, .settings]
    super.init(parent: parent,pages: pages)
  }
}
```

And `MarketplaceCoordinator`'s view controller contains a button which navigates to `SettingCoordinator`.

if `HomeCoordinator`just implemented `TabbarPage` protocol then `coordinator(parent: Coordinator)` could be declared inside coordinator and I could just pass a void block `showSettings` (or other similar ways). The problem is `HomeRouter` is passed as a generic param, and I don't know how to deal with it.
Your example doesn't cover this situation too.

The only solution I found looks strange - I override `init` method and iterate through all `children` to find a coordinator I need.

**Comment by felilo** [comment]
You should set new value of `currentPage` variable like `setTabProgrammatically` function

``` swift
class HomeCoordinator: TabbarCoordinator<HomeRouter> {

  public init(parent: Coordinator) {
    let pages: [Router] = [.marketplace, .settings]
    super.init(parent: parent,pages: pages)
  }
  
  func setTabProgrammatically() {
   currentPage = .settings
  }
}
```

**Comment by Gargo** [comment]
@felilo you didn't understand the problem. I know that I can use `currentPage = .settings`.
The problem is how to call `setTabProgrammatically` from `MarketplaceCoordinator` or its view controllers.

**Comment by felilo** [comment]
This problem does not belong to this library. To solve it you can implement techniques via Notification Center, reactive programming (RXSwift, Combine, Subscriptions) and so on.

**Comment by Gargo** [comment]
@felilo currently I use dependency injection but it looks awful because instead of passing all the necessary params on child coordinator creation I should create a coordinator, then find and get it back from `children` property. And only then I can set all the necessary variables.

I think this library has at least one problem - `setupPages` is a private method. If it was open I could override it and set the coordinator properties immediately after creation.

**Comment by felilo** [comment]
Maybe dependency injection is not the best approach. I leave you other way to solve it.
https://developer.apple.com/documentation/foundation/notificationcenter

**Comment by Gargo** [comment]
@felilo tabbar coordinator initializes 2 child coordinators and even has constant direct links to them. In this case sending notifications instead of dependency injection looks strange.

**Comment by felilo** [comment]
please send the repo link or a complete snippet code about what you are doing
