### ISSUE TITLE
Push view controller over tabbar coordinator?

### ISSUE THREAD

**Issue by Gargo** [felilo/ALCoordinator#66]
I have a tabbar coordinator in which one of the child view controllers should push fullscreen view controller.

The problem is if this view controller just pushes another view controller then tabbar is visible. If I try to push a view controller inside tabbar controllers' navigation controller, that view controller becomes hidden somewhere in the background (I play a sound on it and hear this sound but don't see the view controller by itself).

It seems you present `UITabBarController` directly instead of "UINavigationController(UITabBarController)` which is recommended by `Coordinator` pattern.

**Comment by Gargo** [comment]
found out that I can use `hidesBottomBarWhenPushed = true` but anyways it doesn't cancel the fact `UITabBarController` doesn't have its own `UINavigationController`

**Comment by alozano-applaudo** [comment]
In the latest version (1.0.0) the issue was resolved.
